# Node.js ka light version use karenge
FROM node:18-alpine

# Working directory set kar rahe hains
WORKDIR /app

# pehle package.json aur package-lock.json copy karo
COPY package*.json ./

# dependencies install karo
RUN npm install

# ab sari backend ki files copy karo
COPY . .

# port expose karo (jo tumhare backend pe chal raha ho)
EXPOSE 5000

# app ko start karo
CMD ["node", "index.js"]
